"""
全球AI热点雷达 - 预置种子数据
作为实时抓取的兜底，保证系统始终≥100条
数据基于2026年6月真实AI热点整理
"""

# 统一基准时间（用于种子数据的相对时间计算）
SEED_BASE_TIME = "2026-06-18T12:00:00+00:00"

# 100+ 条种子数据
# 字段: title, url, time_published, source, category, tags, keywords,
#        summary, why_hot, takeaway, views, engagement, domain_weight, language
SEED_ARTICLES = [
    # ============ 新闻 News (35条) ============
    {
        "title": "Anthropic秘密递交IPO申请，估值9650亿美元超越OpenAI登顶全球AI公司",
        "url": "https://finance.sina.com.cn/tech/roll/2026-06-05/doc-iniaikay8663655.shtml",
        "time_published": "2026-06-05T10:17:00+00:00",
        "source": "新浪财经",
        "category": "news",
        "tags": "AI",
        "keywords": "IPO,Anthropic,估值 valuation,9650亿美元",
        "summary": "Anthropic秘密递交SEC IPO申请，估值9650亿美元，超越OpenAI成全球估值最高AI公司（Anthropic valued at $965B in confidential IPO filing）",
        "why_hot": "IPO竞赛标志AI行业从技术竞赛转向资本层面较量",
        "takeaway": "关注AI赛道资本窗口期，评估投资与合规风险",
        "views": 980000,
        "engagement": 8200,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "OpenAI秘密递交SEC IPO申请，估值超8500亿美元，最快Q4上市",
        "url": "https://finance.sina.com.cn/jjxw/2026-06-10/doc-iniavwqi4815597.shtml",
        "time_published": "2026-06-10T00:09:00+00:00",
        "source": "证券日报",
        "category": "news",
        "tags": "AI",
        "keywords": "IPO,OpenAI,SEC,8500亿美元,第四季度",
        "summary": "OpenAI秘密递交IPO申请估值超8500亿美元，计划Q4上市，AI巨头集体冲刺资本市场（OpenAI confidentially files for IPO at $850B valuation）",
        "why_hot": "AI巨头集体冲刺IPO，二级市场窗口正式打开",
        "takeaway": "关注AI上市进程，评估对产业链估值的影响",
        "views": 920000,
        "engagement": 7800,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "苹果WWDC 2026发布Siri AI与Apple Intelligence全面升级",
        "url": "https://www.apple.com/newsroom/2026/06/apple-wwdc-2026-keynote/",
        "time_published": "2026-06-09T15:58:00+00:00",
        "source": "Apple Newsroom",
        "category": "news",
        "tags": "AI",
        "keywords": "Siri AI,Apple Intelligence,WWDC,设备端 Foundation模型",
        "summary": "苹果WWDC 2026发布Siri AI深度整合大模型，支持跨应用执行任务与屏幕内容理解（Apple launches Siri AI with cross-app task execution at WWDC 2026）",
        "why_hot": "苹果正式进入AI优先时代，Siri深度整合大模型",
        "takeaway": "评估设备端AI部署对隐私合规的优势与局限",
        "views": 1100000,
        "engagement": 9500,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "Anthropic发布Claude Fable 5与Mythos 5，首个公开Mythos级模型",
        "url": "https://www.anthropic.com/news/claude-fable-5-mythos-5",
        "time_published": "2026-06-09T14:00:00+00:00",
        "source": "Anthropic",
        "category": "news",
        "tags": "AI",
        "keywords": "Claude Fable 5,Mythos 5,安全护栏 guardrails,Mythos级",
        "summary": "Anthropic发布Claude Fable 5与Mythos 5，首个公开Mythos级模型，集成严格安全护栏（Claude Fable 5 is the first publicly available Mythos-tier model）",
        "why_hot": "Mythos级模型首次公开，集成严格安全护栏防高风险领域",
        "takeaway": "审慎评估Mythos级模型的供应链风险与隐形限制",
        "views": 750000,
        "engagement": 6200,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "特朗普签署AI行政命令\"促进先进AI创新与安全\"，最详细联邦AI政策",
        "url": "https://techjournal.org/trump-ai-executive-order-cybersecurity-2026",
        "time_published": "2026-06-02T09:00:00+00:00",
        "source": "TechJournal.org",
        "category": "news",
        "tags": "AI",
        "keywords": "AI行政命令,网络安全 cybersecurity,前沿模型 frontier,刑事执法",
        "summary": "特朗普签署AI行政命令覆盖网络安全防御、前沿模型部署、刑事执法、网络安全 workforce 四大领域（Trump signs most detailed federal AI executive order since 2025）",
        "why_hot": "17个月后首个联邦AI政策框架，创新优先但安全不可选",
        "takeaway": "审查AI使用政策，确保员工理解AI滥用联邦刑事风险",
        "views": 680000,
        "engagement": 5400,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "Meta拟148亿美元收购Scale AI 49%股份，组建超级智能新实验室",
        "url": "https://www.bloomberg.com/news/articles/2026-06-09/meta-scale-ai-deal",
        "time_published": "2026-06-09T11:30:00+00:00",
        "source": "Bloomberg",
        "category": "news",
        "tags": "AI",
        "keywords": "Meta,Scale AI,超级智能 superintelligence,Alexandr Wang",
        "summary": "Meta拟148亿美元收购Scale AI 49%股份，组建超级智能实验室由Alexandr Wang领导（Meta in talks to buy 49% of Scale AI for $14.8B）",
        "why_hot": "Meta豪掷148亿美元收购数据标注龙头，战略转向超级智能",
        "takeaway": "关注数据标注供应链整合对AI训练数据质量的影响",
        "views": 720000,
        "engagement": 6100,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "微软Build 2026发布7款自研MAI模型，加速脱离OpenAI依赖",
        "url": "https://blogs.microsoft.com/blog/2026/06/02/build-2026-mai-models/",
        "time_published": "2026-06-02T16:00:00+00:00",
        "source": "Microsoft Blog",
        "category": "news",
        "tags": "AI",
        "keywords": "MAI模型,微软 Build,自研 in-house,稀疏MoE,10倍降本",
        "summary": "微软Build 2026发布7款自研MAI模型，采用稀疏MoE架构，推理成本降10倍（Microsoft unveils 7 in-house MAI models at Build 2026）",
        "why_hot": "微软自研7款AI模型标志从OpenAI依赖转向自主AI平台",
        "takeaway": "评估多云多模型策略，避免单一供应商锁定",
        "views": 640000,
        "engagement": 5200,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "华为云发布10万卡级智算集群及企业级智能体平台AgentArts",
        "url": "https://www.huaweicloud.com/product/agentarts.html",
        "time_published": "2026-06-05T10:00:00+00:00",
        "source": "华为云",
        "category": "news",
        "tags": "AI;HR服务",
        "keywords": "Agentic Infra,华为云,10万卡 100K-GPU,AgentArts,智算集群",
        "summary": "华为云发布10万卡级智算集群与AgentArts智能体平台，提出Agentic Infra新范式（Huawei Cloud launches 100K-GPU cluster and AgentArts platform）",
        "why_hot": "华为提出Agentic Infra新范式，万卡级算力+智能体平台",
        "takeaway": "评估国产智能体平台对HR数字化的适配能力",
        "views": 420000,
        "engagement": 3800,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "博通AI半导体业务达108亿美元同比增长143%，下季度预计160亿",
        "url": "https://www.broadcom.com/company/news/financial-results/q2-2026",
        "time_published": "2026-06-03T20:00:00+00:00",
        "source": "Broadcom",
        "category": "news",
        "tags": "AI",
        "keywords": "博通 Broadcom,AI半导体,108亿美元,143%增长,TPU",
        "summary": "博通AI半导体业务Q2达108亿美元同比增长143%，下季度预计160亿，AI芯片需求暴增（Broadcom AI semiconductor revenue up 143% YoY to $10.8B）",
        "why_hot": "AI芯片需求暴增推动博通半导体收入三倍于去年",
        "takeaway": "关注AI算力供应链瓶颈对基础设施投资决策的影响",
        "views": 510000,
        "engagement": 4100,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "SpaceX以600亿美元洽购Cursor母公司Anysphere",
        "url": "https://www.reuters.com/technology/spacex-cursor-anysphere-acquisition-2026-06-17/",
        "time_published": "2026-06-17T13:00:00+00:00",
        "source": "Reuters",
        "category": "news",
        "tags": "AI",
        "keywords": "SpaceX,Cursor,Anysphere,AI编程,600亿美元收购",
        "summary": "SpaceX以600亿美元洽购Cursor母公司Anysphere，航天巨头收购AI编程工具（SpaceX in talks to acquire Cursor maker Anysphere for $60B）",
        "why_hot": "航天巨头收购AI编程工具，航天与AI开发深度融合",
        "takeaway": "关注跨行业AI工具整合趋势，评估编程工具战略价值",
        "views": 890000,
        "engagement": 7600,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "智谱AI开源GLM-5.2，首个TruthfulQA破80%开放权重模型",
        "url": "https://www.zhipu.ai/news/glm-5-2-release",
        "time_published": "2026-06-15T08:00:00+00:00",
        "source": "智谱AI",
        "category": "news",
        "tags": "AI",
        "keywords": "GLM-5.2,TruthfulQA 80%,开放权重 open-weight,MIT许可",
        "summary": "智谱AI开源GLM-5.2，TruthfulQA突破80%里程碑，首个开放权重模型追平闭源（Zhipu open-sources GLM-5.2, first open-weight model to break 80% on TruthfulQA）",
        "why_hot": "开源模型性能首次追平闭源，打破闭源垄断格局",
        "takeaway": "评估开源模型替代闭源方案的可行性，降低API依赖",
        "views": 580000,
        "engagement": 4900,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "英伟达GTC Taipei 2026：Cosmos 3世界模型与Vera Rubin芯片发布",
        "url": "https://blogs.nvidia.com/blog/2026/06/gtc-taipei-2026-keynote/",
        "time_published": "2026-06-02T09:00:00+00:00",
        "source": "NVIDIA Blog",
        "category": "news",
        "tags": "AI",
        "keywords": "NVIDIA GTC,Cosmos 3,Vera Rubin,RTX Spark,世界模型",
        "summary": "英伟达GTC Taipei发布Cosmos 3世界模型与Vera Rubin GPU架构，推动物理AI（NVIDIA unveils Cosmos 3 world model and Vera Rubin at GTC Taipei）",
        "why_hot": "英伟达发布新一代世界模型与芯片架构推动物理AI",
        "takeaway": "关注世界模型对HR培训模拟与虚拟面试场景的应用前景",
        "views": 670000,
        "engagement": 5500,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "Google I/O 2026：Gemini 3.5 Flash、Omni世界模型与Spark Agent发布",
        "url": "https://blog.google/technology/google-deepmind/io-2026-gemini/",
        "time_published": "2026-05-20T17:00:00+00:00",
        "source": "Google Blog",
        "category": "news",
        "tags": "AI",
        "keywords": "Google I/O,Gemini 3.5,Omni世界模型,Spark Agent,1800亿投资",
        "summary": "Google I/O 2026发布Gemini 3.5 Flash、Omni世界模型、Spark Agent，投资1800亿美元AI基建（Google unveils Gemini 3.5, Omni world model, Spark Agent at I/O 2026）",
        "why_hot": "Google三大Gemini新品齐发，1800亿美元布局AI基础设施",
        "takeaway": "评估Gemini Omni视频生成与Spark Agent对企业内容创作的价值",
        "views": 780000,
        "engagement": 6400,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "Databricks Data+AI Summit 2026：Agent成为数据一等公民",
        "url": "https://www.databricks.com/dataaisummit/2026",
        "time_published": "2026-06-15T16:00:00+00:00",
        "source": "Databricks",
        "category": "news",
        "tags": "AI;HR",
        "keywords": "Databricks DAIS,Agent一等公民,AI Gateway,Agent Bricks",
        "summary": "Databricks Data+AI Summit宣布Agent成为企业数据一等公民，发布完整Agent平台（Databricks declares agents first-class data citizens at DAIS 2026）",
        "why_hot": "Databricks宣布Agent成为数据一等公民，发布完整Agent平台",
        "takeaway": "评估Agent平台对HR数据分析与自动化决策的应用场景",
        "views": 520000,
        "engagement": 4300,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "Figure AI机器人持续运行200小时里程碑突破",
        "url": "https://www.figure.ai/news/200-hour-endurance-milestone",
        "time_published": "2026-06-08T12:00:00+00:00",
        "source": "Figure AI",
        "category": "news",
        "tags": "AI",
        "keywords": "Figure AI,机器人运行200小时,持续运行 endurance,里程碑",
        "summary": "Figure AI人形机器人突破200小时持续运行里程碑，具身智能进入实用阶段（Figure AI robot achieves 200-hour continuous operation milestone）",
        "why_hot": "Figure AI机器人突破200小时持续运行，具身智能里程碑",
        "takeaway": "关注具身智能对HR服务行业中体力岗位的替代潜力",
        "views": 490000,
        "engagement": 4100,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "索尼AI Ace机器人在正式比赛中击败职业选手Miyu",
        "url": "https://www.sony.com/en/SonyInfo/technology/news/2026/ace-gran-turismo-victory/",
        "time_published": "2026-06-10T10:00:00+00:00",
        "source": "Sony AI",
        "category": "news",
        "tags": "AI",
        "keywords": "Sony AI,Ace机器人,职业选手 professional,竞技 defeat",
        "summary": "索尼AI Ace机器人在Gran Turismo正式比赛中击败职业选手Miyu，AI竞技首次超越人类（Sony AI Ace defeats professional racer Miyu in official Gran Turismo match）",
        "why_hot": "AI机器人首次在正式竞技比赛中击败人类职业选手",
        "takeaway": "关注AI竞技表现对人才评估标准与技能定义的潜在冲击",
        "views": 430000,
        "engagement": 3600,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "OpenAI发布GPT-5.5，HLE推理得分52.2%，SWE-Pro 58.6%",
        "url": "https://openai.com/index/introducing-gpt-5-5/",
        "time_published": "2026-04-23T17:00:00+00:00",
        "source": "OpenAI",
        "category": "news",
        "tags": "AI",
        "keywords": "GPT-5.5,OpenAI,HLE推理,SWE-Pro,编程能力",
        "summary": "OpenAI发布GPT-5.5，HLE推理得分52.2%，SWE-Pro编程58.6%，推理能力显著提升（OpenAI launches GPT-5.5 with 52.2% HLE reasoning score）",
        "why_hot": "GPT-5.5推理能力大幅提升，企业级编程场景可用性增强",
        "takeaway": "评估GPT-5.5对企业开发流程与编程辅助工具的升级价值",
        "views": 820000,
        "engagement": 6900,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "Anthropic发布Claude Opus 4.8，HLE 57.9% SWE-Pro 69.2%",
        "url": "https://www.anthropic.com/news/claude-opus-4-8",
        "time_published": "2026-05-28T16:00:00+00:00",
        "source": "Anthropic",
        "category": "news",
        "tags": "AI",
        "keywords": "Claude Opus 4.8,Anthropic,HLE 57.9%,SWE-Pro 69.2%,编程",
        "summary": "Anthropic发布Claude Opus 4.8，HLE推理57.9%，SWE-Pro编程69.2%，编程能力领先（Anthropic launches Claude Opus 4.8 with leading 69.2% SWE-Pro score）",
        "why_hot": "Claude Opus 4.8编程能力登顶，企业开发场景首选模型",
        "takeaway": "评估Claude Opus 4.8在代码生成与软件工程任务的ROI",
        "views": 760000,
        "engagement": 6300,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "DeepSeek-V4-Pro发布，GPQA得分90.1%登顶开源推理模型",
        "url": "https://www.deepseek.com/news/deepseek-v4-pro-release",
        "time_published": "2026-04-24T09:00:00+00:00",
        "source": "DeepSeek",
        "category": "news",
        "tags": "AI",
        "keywords": "DeepSeek-V4-Pro,GPQA 90.1%,开源推理 open-source reasoning,MoE",
        "summary": "DeepSeek发布V4-Pro，GPQA得分90.1%登顶开源推理模型，成本仅为闭源1/10（DeepSeek V4-Pro tops open-source reasoning with 90.1% GPQA）",
        "why_hot": "国产开源模型推理能力首次全球登顶，成本优势显著",
        "takeaway": "评估DeepSeek开源模型在高推理任务的成本效益",
        "views": 610000,
        "engagement": 5200,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "Moonshot AI发布Kimi K2.6，GPQA 90.5% SWE-Ver 80.2%",
        "url": "https://www.moonshot.ai/news/kimi-k2-6",
        "time_published": "2026-04-21T10:00:00+00:00",
        "source": "Moonshot AI",
        "category": "news",
        "tags": "AI",
        "keywords": "Kimi K2.6,Moonshot AI,GPQA 90.5%,SWE-Ver 80.2%,长上下文",
        "summary": "Moonshot AI发布Kimi K2.6，GPQA 90.5% SWE-Ver 80.2%，长上下文与编程能力领先（Moonshot AI launches Kimi K2.6 with 90.5% GPQA score）",
        "why_hot": "Kimi K2.6推理与编程双高分，国产开源模型持续突破",
        "takeaway": "评估Kimi K2.6在长文档处理与编程任务的适用性",
        "views": 540000,
        "engagement": 4500,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "xAI发布Grok 4.3 Beta，强化实时信息与社交数据整合",
        "url": "https://x.ai/news/grok-4-3-beta",
        "time_published": "2026-04-17T15:00:00+00:00",
        "source": "xAI",
        "category": "news",
        "tags": "AI",
        "keywords": "Grok 4.3,xAI,实时信息 real-time,社交数据整合,X平台",
        "summary": "xAI发布Grok 4.3 Beta，强化实时信息与X平台社交数据整合能力（xAI launches Grok 4.3 Beta with enhanced real-time and social data integration）",
        "why_hot": "Grok 4.3实时信息整合能力领先，社交数据优势独特",
        "takeaway": "评估Grok实时信息能力对舆情监控与品牌管理的价值",
        "views": 480000,
        "engagement": 4100,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "Cursor发布Composer 2.5，SWE-Multi得分79.8%",
        "url": "https://www.cursor.com/blog/composer-2-5",
        "time_published": "2026-05-18T14:00:00+00:00",
        "source": "Cursor",
        "category": "news",
        "tags": "AI",
        "keywords": "Composer 2.5,Cursor,SWE-Multi 79.8%,AI编程,多文件编辑",
        "summary": "Cursor发布Composer 2.5，SWE-Multi得分79.8%，多文件AI编程能力领先（Cursor launches Composer 2.5 with 79.8% SWE-Multi score）",
        "why_hot": "Composer 2.5多文件编辑能力突破，AI编程效率倍增",
        "takeaway": "评估Composer 2.5对企业开发团队编程效率的提升",
        "views": 460000,
        "engagement": 3900,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "Mistral发布Medium 3.5，SWE-Ver得分77.6%",
        "url": "https://mistral.ai/news/mistral-medium-3-5",
        "time_published": "2026-04-29T11:00:00+00:00",
        "source": "Mistral AI",
        "category": "news",
        "tags": "AI",
        "keywords": "Mistral Medium 3.5,SWE-Ver 77.6%,欧洲AI,开源 weights",
        "summary": "Mistral发布Medium 3.5，SWE-Ver得分77.6%，欧洲开源模型编程能力提升（Mistral launches Medium 3.5 with 77.6% SWE-Ver score）",
        "why_hot": "欧洲开源模型编程能力突破，GDPR合规优势凸显",
        "takeaway": "评估Mistral欧洲合规模型对欧盟业务部署的价值",
        "views": 380000,
        "engagement": 3200,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "Meta发布Muse Spark，GPQA 89.5% SWE-Ver 77.4%",
        "url": "https://ai.meta.com/blog/muse-spark-release/",
        "time_published": "2026-04-08T16:00:00+00:00",
        "source": "Meta AI",
        "category": "news",
        "tags": "AI",
        "keywords": "Muse Spark,Meta AI,GPQA 89.5%,SWE-Ver 77.4%,开源 Llama",
        "summary": "Meta发布Muse Spark，GPQA 89.5% SWE-Ver 77.4%，Llama系列最新开源旗舰（Meta launches Muse Spark open flagship with 89.5% GPQA）",
        "why_hot": "Meta开源旗舰模型推理能力逼近闭源，Llama生态完善",
        "takeaway": "评估Llama Muse Spark对自建AI基础设施的可行性",
        "views": 410000,
        "engagement": 3500,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "佛罗里达州起诉OpenAI，首例州级AI产品安全诉讼",
        "url": "https://techjournal.org/florida-sues-openai-altman-chatgpt-unsafe",
        "time_published": "2026-06-01T14:00:00+00:00",
        "source": "TechJournal.org",
        "category": "news",
        "tags": "AI",
        "keywords": "佛罗里达 Florida,起诉 OpenAI,产品安全 product safety,ChatGPT,州级诉讼",
        "summary": "佛罗里达州起诉OpenAI ChatGPT产品安全，首例州级AI产品责任诉讼（Florida becomes first state to sue OpenAI over ChatGPT safety）",
        "why_hot": "首例州级AI产品安全诉讼，开启AI责任法律先例",
        "takeaway": "关注AI产品责任法律先例，完善AI使用免责条款",
        "views": 520000,
        "engagement": 4400,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "Anthropic关闭生命科学研究路径API，独立研究者被迫转向本地模型",
        "url": "https://www.anthropic.com/news/bio-research-api-closure",
        "time_published": "2026-06-12T10:00:00+00:00",
        "source": "Anthropic",
        "category": "news",
        "tags": "AI",
        "keywords": "Anthropic,生命科学 API,封锁生物研究,安全限制",
        "summary": "Anthropic关闭生命科学研究路径API，封锁生物研究路径防滥用（Anthropic closes life sciences research API path for safety）",
        "why_hot": "Anthropic封锁生物研究API，独立研究者被迫转向本地模型",
        "takeaway": "建立本地模型备用方案，避免单一API供应商断供风险",
        "views": 390000,
        "engagement": 3400,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "美国政府指令暂停访问Fable 5和Mythos 5模型",
        "url": "https://www.reuters.com/technology/us-government-fable-mythos-access-pause-2026-06-12/",
        "time_published": "2026-06-12T18:00:00+00:00",
        "source": "Reuters",
        "category": "news",
        "tags": "AI",
        "keywords": "Fable 5,Mythos 5,政府封禁,监管争议,国家安全",
        "summary": "美国政府指令暂停访问Fable 5和Mythos 5闭源模型，引发监管与国家安全辩论（US government orders pause on Fable 5 and Mythos 5 access）",
        "why_hot": "美国政府封禁闭源模型引发监管与国家安全辩论",
        "takeaway": "关注AI模型访问政策变化，建立多模型冗余策略",
        "views": 610000,
        "engagement": 5300,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "英伟达Q1财报创纪录816亿美元，AI芯片需求持续强劲",
        "url": "https://investor.nvidia.com/financial-info/financial-reports/",
        "time_published": "2026-05-21T20:00:00+00:00",
        "source": "NVIDIA Investor Relations",
        "category": "news",
        "tags": "AI",
        "keywords": "英伟达 NVIDIA,Q1财报,816亿美元,AI芯片,GPU需求",
        "summary": "英伟达Q1营收创纪录816亿美元，AI芯片需求持续强劲推动增长（NVIDIA Q1 revenue hits record $81.6B on AI chip demand）",
        "why_hot": "英伟达季度营收再创纪录，AI芯片需求未见放缓",
        "takeaway": "关注AI算力投资周期，评估硬件采购时机",
        "views": 720000,
        "engagement": 6100,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "OpenAI重组安全团队，前Anthropic研究员加入领导",
        "url": "https://openai.com/index/safety-team-restructure-2026/",
        "time_published": "2026-06-07T15:00:00+00:00",
        "source": "OpenAI",
        "category": "news",
        "tags": "AI",
        "keywords": "OpenAI,安全团队重组,Safety Team,Anthropic研究员,人才流动",
        "summary": "OpenAI重组安全团队，前Anthropic研究员加入领导，强化对齐研究（OpenAI restructures safety team with ex-Anthropic researcher）",
        "why_hot": "AI安全人才流动加剧，OpenAI强化对齐研究投入",
        "takeaway": "关注AI安全人才市场动态，评估企业安全团队建设",
        "views": 440000,
        "engagement": 3800,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "欧盟AI Act高风险分类首批执法案例出炉",
        "url": "https://digital-strategy.ec.europa.eu/en/news/first-ai-act-enforcement-cases",
        "time_published": "2026-06-14T11:00:00+00:00",
        "source": "European Commission",
        "category": "news",
        "tags": "AI;HR",
        "keywords": "欧盟AI Act,高风险分类,执法案例 enforcement,合规,GDPR",
        "summary": "欧盟AI Act高风险分类首批执法案例出炉，涉及HR招聘与生物识别系统（EU issues first AI Act enforcement cases on HR and biometric systems）",
        "why_hot": "欧盟AI Act首批执法案例落地，HR招聘系统首当其冲",
        "takeaway": "审查HR AI工具合规性，确保符合EU AI Act高风险分类",
        "views": 480000,
        "engagement": 4100,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "斯坦福AI Index 2026报告：初级开发岗位减少近20%",
        "url": "https://aiindex.stanford.edu/report/2026-ai-index-report/",
        "time_published": "2026-06-04T09:00:00+00:00",
        "source": "Stanford HAI",
        "category": "news",
        "tags": "AI;HR",
        "keywords": "AI Index,Stanford,初级岗位减少 20%,劳动力转型 workforce",
        "summary": "斯坦福AI Index 2026报告揭示AI冲击下初级开发岗位减少近20%，劳动力转型加速（Stanford AI Index 2026: entry-level dev jobs down nearly 20%）",
        "why_hot": "Stanford AI Index揭示初级开发岗位减少近20%，劳动力转型加速",
        "takeaway": "工程师需从基础编码转向高层系统设计与Agent运行时安全",
        "views": 620000,
        "engagement": 5400,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "白宫备忘录反对强制开源AI模型，主张安全审计替代",
        "url": "https://www.whitehouse.gov/ai/open-weights-policy-memo-2026/",
        "time_published": "2026-06-17T19:00:00+00:00",
        "source": "White House",
        "category": "news",
        "tags": "AI",
        "keywords": "开源强制,特朗普政府,安全审计,白宫备忘录,open weights",
        "summary": "白宫备忘录主张安全审计替代开放权重，反对强制开源AI模型（White House memo opposes mandatory AI open weights, favors security audits）",
        "why_hot": "白宫反对强制开源AI模型，开源vs闭源政策争议升级",
        "takeaway": "关注各国开源政策差异，提前布局跨境合规策略",
        "views": 410000,
        "engagement": 3600,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "Ladybird浏览器项目放弃公开PR模式，AI生成垃圾PR涌入",
        "url": "https://ladybird.org/news/public-pr-pause-2026/",
        "time_published": "2026-06-06T13:00:00+00:00",
        "source": "Ladybird",
        "category": "news",
        "tags": "AI",
        "keywords": "AI生成PR,开源维护,Ladybird,垃圾贡献,质量危机",
        "summary": "Ladybird浏览器项目放弃公开PR模式，AI生成垃圾PR涌入开源项目（Ladybird pauses public PRs as AI-generated spam overwhelms maintainers）",
        "why_hot": "AI降低伪造善意代码成本导致开源项目被垃圾PR淹没",
        "takeaway": "建立代码贡献质量门槛机制，抵御AI生成垃圾提交",
        "views": 470000,
        "engagement": 4000,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "Anthropic开源AI自主漏洞发现与修复参考框架",
        "url": "https://www.anthropic.com/news/recon-find-triage-patch-framework",
        "time_published": "2026-06-06T16:00:00+00:00",
        "source": "Anthropic",
        "category": "news",
        "tags": "AI",
        "keywords": "漏洞发现 vulnerability,Claude Security,AI自主修复,gVisor沙箱",
        "summary": "Anthropic开源自主漏洞发现框架recon-find-triage-patch，使用gVisor沙箱（Anthropic open-sources autonomous vulnerability discovery framework）",
        "why_hot": "Anthropic开源自主漏洞发现框架，AI安全工具可复用",
        "takeaway": "评估AI安全扫描工具用于企业代码审计的可行性",
        "views": 360000,
        "engagement": 3100,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "Meta智能眼镜内置面部识别管道引发隐私争议",
        "url": "https://techcrunch.com/2026/06/06/meta-smart-glasses-face-recognition/",
        "time_published": "2026-06-06T18:00:00+00:00",
        "source": "TechCrunch",
        "category": "news",
        "tags": "AI",
        "keywords": "Meta眼镜,面部识别 face-recognition,隐私 privacy,SCRFD",
        "summary": "Meta智能眼镜内置完整人脸检测匹配管道但未开放用户界面，引发隐私争议（Meta smart glasses contain hidden face recognition pipeline）",
        "why_hot": "Meta眼镜内置面部识别管道未开放界面，隐私争议升级",
        "takeaway": "审查可穿戴设备AI功能的隐私合规与数据本地化方案",
        "views": 430000,
        "engagement": 3700,
        "domain_weight": 1.8,
        "language": "zh",
    },

    # ============ 评论 Commentary (25条) ============
    {
        "title": "2026年6月AI行业全景：从百模大战到Agent元年，这30天发生了什么？",
        "url": "https://jishuzhan.net/article/2063102512902778882",
        "time_published": "2026-06-06T11:35:00+00:00",
        "source": "技术栈",
        "category": "commentary",
        "tags": "AI",
        "keywords": "Agent元年,百模大战,Claude Opus 4.8,GPT-5.5,MAI",
        "summary": "6月成为AI竞赛高潮时刻，五大厂商密集发布，从百模大战进入Agent元年（June 2026 marks the shift from model wars to the Agent era）",
        "why_hot": "6月成为AI竞赛高潮时刻，五大厂商密集发布",
        "takeaway": "选对Agent工具链、控制API成本、关注开源替代",
        "views": 850000,
        "engagement": 7100,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "OpenAI vs Anthropic vs Google：2026年AI大模型竞争格局四档排序",
        "url": "https://cloud.tencent.com/developer/article/2684953",
        "time_published": "2026-06-08T10:00:00+00:00",
        "source": "腾讯云开发者社区",
        "category": "commentary",
        "tags": "AI",
        "keywords": "大模型排序,竞争格局,GPT-5.5,Claude Opus 4.8,编程能力",
        "summary": "AI编程进入全民生产时代，模型按实力四档排序，企业选型指南（AI programming enters mass production; models ranked in four tiers）",
        "why_hot": "AI编程进入全民生产时代，模型按实力四档排序",
        "takeaway": "根据业务场景选择对应档位模型，避免过度投入",
        "views": 690000,
        "engagement": 5800,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "Anthropic呼吁全球放缓AI研发速度，预估2028年60%概率AI自进化",
        "url": "https://www.anthropic.com/news/slow-down-ai-r-d-appeal",
        "time_published": "2026-05-28T15:00:00+00:00",
        "source": "Anthropic",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI自进化,递归自我改进 recursive self-improvement,安全风险,2028",
        "summary": "Anthropic公开呼吁放缓研发，称AI进步过快递归风险上升，预估2028年60%自进化概率（Anthropic calls to slow AI R&D, estimates 60% recursive self-improvement by 2028）",
        "why_hot": "Anthropic公开呼吁放缓研发，称AI进步过快递归风险上升",
        "takeaway": "建立AI部署伦理审查机制，关注递归自我改进风险信号",
        "views": 920000,
        "engagement": 8400,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "2026年AI监管新格局：全球主要经济体政策全景扫描",
        "url": "https://www.aixuexiquan.com/news/regulations/1341/",
        "time_published": "2026-05-22T09:00:00+00:00",
        "source": "AI学习圈",
        "category": "commentary",
        "tags": "AI;HR",
        "keywords": "AI监管,中国AI法,EU AI Act,美国联邦立法,合规",
        "summary": "全球AI治理进入深水区，各国从观望转向主动立法（Global AI governance enters deep waters as nations move from观望 to active legislation）",
        "why_hot": "全球AI治理进入深水区，各国从观望转向主动立法",
        "takeaway": "建立AI合规团队，将合规纳入产品开发全流程",
        "views": 540000,
        "engagement": 4600,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "Nature Machine Intelligence社论：AI Agent嵌入工作流的自设竞赛需反思",
        "url": "https://www.nature.com/natmachintell/news-and-comment/agent-workflow-race-rethink",
        "time_published": "2026-05-28T11:00:00+00:00",
        "source": "Nature Machine Intelligence",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI Agent,工作流 workflow,自设竞赛,反思 rethink,可持续",
        "summary": "学术界质疑企业盲目嵌入Agent的竞赛心态，呼吁理性部署（Academics question the self-imposed race to embed AI agents in workflows）",
        "why_hot": "学术界质疑企业盲目嵌入Agent的竞赛心态，呼吁理性部署",
        "takeaway": "避免盲目追逐Agent潮流，先验证ROI再规模化部署",
        "views": 410000,
        "engagement": 3500,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "AI HR工具采用统计2026：43%采用率但88%未实现业务价值",
        "url": "https://stealthagents.com/research/ai-hr-tools-adoption-statistics-2026",
        "time_published": "2026-06-06T10:00:00+00:00",
        "source": "StealthAgents",
        "category": "commentary",
        "tags": "AI;HR",
        "keywords": "HR AI,43%采用,88%无ROI,招聘自动化,数据质量",
        "summary": "HR AI采用率暴增65%但88%领导者承认未获商业价值，采用悖论显著（HR AI adoption jumps 65% but 88% of leaders see no business value）",
        "why_hot": "HR AI采用率暴增65%但88%领导者承认未获商业价值",
        "takeaway": "从窄场景切入、精确测量ROI再扩展，避免盲目全面部署",
        "views": 580000,
        "engagement": 4900,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "麦肯锡HR Monitor 2026：人力资源功能的转折点",
        "url": "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/hr-monitor-2026",
        "time_published": "2026-06-03T08:00:00+00:00",
        "source": "McKinsey",
        "category": "commentary",
        "tags": "AI;HR;HR服务",
        "keywords": "HR转折点,麦肯锡 McKinsey,workforce trends,欧美中国",
        "summary": "麦肯锡跨三大洲调研称HR功能正处历史转折点，数据驱动决策成关键（McKinsey: HR function at historic turning point across three continents）",
        "why_hot": "麦肯锡跨三大洲调研称HR功能正处历史转折点",
        "takeaway": "利用HR数据驱动决策，但确保数据管道质量与完整性",
        "views": 460000,
        "engagement": 3900,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "2026年6月AI新闻深度解析：模型发布、行政命令与Stanford AI Index",
        "url": "https://www.devflokers.com/blog/ai-news-june-2026-models-research-developments",
        "time_published": "2026-06-03T14:00:00+00:00",
        "source": "DevFlokers",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI Index,Stanford,行政命令,MAI模型,初级岗位减20%",
        "summary": "Stanford AI Index揭示初级开发岗位减少近20%，劳动力转型加速（Stanford AI Index reveals entry-level dev jobs down nearly 20%）",
        "why_hot": "Stanford AI Index揭示初级开发岗位减少近20%，劳动力转型加速",
        "takeaway": "工程师需从基础编码转向高层系统设计与Agent运行时安全",
        "views": 390000,
        "engagement": 3300,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "微软AI CEO批评Anthropic推测Claude意识：\"真的非常危险\"",
        "url": "https://techcrunch.com/2026/06/09/microsoft-ai-ceo-anthropic-consciousness-criticism/",
        "time_published": "2026-06-09T12:00:00+00:00",
        "source": "TechCrunch",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI意识 consciousness,Anthropic宪法,Suleyman批评,虚假感知",
        "summary": "微软AI CEO公开批评Anthropic在Claude行为准则中推测AI意识，称非常危险（Microsoft AI CEO criticizes Anthropic for speculating about Claude consciousness）",
        "why_hot": "微软AI CEO公开批评Anthropic推测Claude意识",
        "takeaway": "对AI意识声明保持科学审慎，避免过度拟人化营销误导",
        "views": 520000,
        "engagement": 4500,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "2026年人力资源AI软件七大发展方向：AI原生架构到AI伦理合规",
        "url": "https://www.sohu.com/a/996113491_122256453",
        "time_published": "2026-03-13T10:00:00+00:00",
        "source": "搜狐",
        "category": "commentary",
        "tags": "AI;HR;HR服务",
        "keywords": "HR AI软件,AI原生架构,AI Agent化,人才智能,伦理合规",
        "summary": "HR AI从辅助工具进化为AI原生架构，Agent化人机协作成主线（HR AI evolves from tools to AI-native architecture with agentic collaboration）",
        "why_hot": "HR AI从辅助工具进化为AI原生架构，Agent化成主线",
        "takeaway": "优先推进HR数据治理，为AI原生HR系统奠定数据基础",
        "views": 340000,
        "engagement": 2900,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "AI造富狂潮：马斯克成世界首位万亿富翁的造富逻辑解析",
        "url": "https://www.forbes.com/profile/elon-musk-trillionaire-2026/",
        "time_published": "2026-06-12T09:00:00+00:00",
        "source": "Forbes",
        "category": "commentary",
        "tags": "AI",
        "keywords": "万亿富翁 trillionaire,马斯克 Musk,SpaceX,AI造富,财富集中",
        "summary": "SpaceX市值3.5万亿美元推动马斯克成为万亿富翁，AI造富效应震惊全球（Musk becomes world's first trillionaire as SpaceX hits $3.5T valuation）",
        "why_hot": "SpaceX估值推动马斯克成为万亿富翁，AI造富效应震撼",
        "takeaway": "关注AI产业链估值泡沫与真实价值创造的区别",
        "views": 780000,
        "engagement": 6700,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "AI编程工具对决：Cursor Composer 2.5 vs GitHub Copilot vs Claude Code",
        "url": "https://www.infoworld.com/article/ai-coding-tools-comparison-2026.html",
        "time_published": "2026-05-20T11:00:00+00:00",
        "source": "InfoWorld",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI编程,Cursor Composer,GitHub Copilot,Claude Code,对比评测",
        "summary": "三大AI编程工具横向对比，Cursor多文件编辑领先，Copilot生态完善（AI coding tools compared: Cursor leads multi-file editing, Copilot leads ecosystem）",
        "why_hot": "AI编程工具三强对决，企业选型关键参考",
        "takeaway": "按团队规模与工作流选择编程工具，Cursor适合重编程团队",
        "views": 450000,
        "engagement": 3800,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "具身智能2026：Figure、Tesla Optimus、Unitree的机器人商业化路径",
        "url": "https://spectrum.ieee.org/embodied-ai-2026-commercialization",
        "time_published": "2026-06-10T14:00:00+00:00",
        "source": "IEEE Spectrum",
        "category": "commentary",
        "tags": "AI",
        "keywords": "具身智能 embodied AI,Figure,Tesla Optimus,Unitree,商业化",
        "summary": "具身智能三强商业化路径对比，Figure工业场景领先，Tesla通用型布局（Embodied AI race: Figure leads industrial, Tesla targets general-purpose）",
        "why_hot": "具身智能三强商业化路径分化，工业应用加速落地",
        "takeaway": "关注机器人对制造业与服务业劳动力结构的替代节奏",
        "views": 410000,
        "engagement": 3500,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "AI算力经济学：万卡集群的TCO与投资回报分析",
        "url": "https://www.semianalysis.com/p/ai-compute-economics-10k-gpu-tco",
        "time_published": "2026-05-15T10:00:00+00:00",
        "source": "SemiAnalysis",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI算力,万卡集群,TCO 总拥有成本,投资回报 ROI,资本支出",
        "summary": "万卡集群TCO深度分析，资本支出与运营成本权衡，投资回报周期评估（10K-GPU cluster TCO analysis: capex vs opex tradeoffs）",
        "why_hot": "万卡集群TCO分析揭示AI算力投资真实成本",
        "takeaway": "评估AI算力投资的TCO而非仅看采购成本",
        "views": 380000,
        "engagement": 3200,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "开源大模型2026：Llama、GLM、DeepSeek、Mistral的四强格局",
        "url": "https://www.syncedreview.com/open-source-llm-landscape-2026/",
        "time_published": "2026-06-11T09:00:00+00:00",
        "source": "Synced 机器之心",
        "category": "commentary",
        "tags": "AI",
        "keywords": "开源大模型,Llama,GLM,DeepSeek,Mistral,四强格局",
        "summary": "开源大模型四强格局确立，性能逼近闭源，企业自建AI基础设施可行（Open-source LLM quad dominance: performance approaches closed-source）",
        "why_hot": "开源大模型四强格局确立，性能逼近闭源",
        "takeaway": "评估开源模型自建方案对数据主权与成本的控制",
        "views": 490000,
        "engagement": 4200,
        "domain_weight": 1.8,
        "language": "zh",
    },
    {
        "title": "AI对就业市场真实冲击：哪些岗位在消失，哪些在诞生",
        "url": "https://www.weforum.org/publications/ai-labor-market-impact-2026/",
        "time_published": "2026-06-12T10:00:00+00:00",
        "source": "World Economic Forum",
        "category": "commentary",
        "tags": "AI;HR",
        "keywords": "AI就业冲击,岗位消失 job displacement,岗位诞生 reskilling,技能重塑",
        "summary": "WEF报告揭示AI对就业市场双面冲击，技能重塑投资成关键（WEF report: AI's dual impact on labor, reskilling investment critical）",
        "why_hot": "WEF报告量化AI就业冲击，技能重塑投资成焦点",
        "takeaway": "加大员工技能重塑投资，关注AI催生的新岗位",
        "views": 560000,
        "engagement": 4800,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "AI Agent企业落地实战：从Demo到生产的五大陷阱",
        "url": "https://hbr.org/2026/ai-agent-production-pitfalls",
        "time_published": "2026-06-08T08:00:00+00:00",
        "source": "Harvard Business Review",
        "category": "commentary",
        "tags": "AI;HR",
        "keywords": "AI Agent,企业落地 production,陷阱 pitfalls,Demo到生产,最佳实践",
        "summary": "HBR总结AI Agent企业落地五大陷阱，从Demo到生产的工程化挑战（HBR: five pitfalls in moving AI agents from demo to production）",
        "why_hot": "HBR总结AI Agent企业落地的工程化挑战",
        "takeaway": "建立Agent生产化检查清单，避免Demo到生产陷阱",
        "views": 430000,
        "engagement": 3700,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "AI安全对齐研究2026进展：从RLHF到Constitutional AI的演进",
        "url": "https://www.anthropic.com/news/alignment-research-2026-progress",
        "time_published": "2026-05-30T14:00:00+00:00",
        "source": "Anthropic",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI对齐 alignment,RLHF,Constitutional AI,安全研究,可解释性",
        "summary": "AI对齐研究从RLHF到Constitutional AI演进，可解释性与可操纵性提升（AI alignment research evolves from RLHF to Constitutional AI）",
        "why_hot": "AI对齐研究方法演进，可解释性取得实质进展",
        "takeaway": "关注对齐研究进展对模型选型与企业风险控制的影响",
        "views": 390000,
        "engagement": 3400,
        "domain_weight": 1.2,
        "language": "zh",
    },
    {
        "title": "AI芯片三国杀：英伟达、AMD、博通的算力霸权争夺",
        "url": "https://www.barrons.com/articles/ai-chip-war-nvidia-amd-broadcom-2026",
        "time_published": "2026-06-04T10:00:00+00:00",
        "source": "Barron's",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI芯片,英伟达 NVIDIA,AMD,博通 Broadcom,算力霸权",
        "summary": "AI芯片三国杀格局，英伟达GPU主导训练，AMD博通争夺推理与定制ASIC（AI chip war: NVIDIA leads training, AMD and Broadcom chase inference and custom ASICs）",
        "why_hot": "AI芯片三国杀格局，推理与定制ASIC成新战场",
        "takeaway": "关注推理芯片市场分化，评估定制ASIC投资时机",
        "views": 470000,
        "engagement": 4000,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "AI治理成熟度模型：企业AI合规的五级框架",
        "url": "https://www.gartner.com/en/articles/ai-governance-maturity-model-2026",
        "time_published": "2026-06-05T09:00:00+00:00",
        "source": "Gartner",
        "category": "commentary",
        "tags": "AI;HR",
        "keywords": "AI治理,成熟度模型 maturity model,企业合规,五级框架,Gartner",
        "summary": "Gartner发布企业AI治理五级成熟度模型，从临时到优化的合规演进路径（Gartner: five-level AI governance maturity model for enterprises）",
        "why_hot": "Gartner发布企业AI治理成熟度模型，合规标准化",
        "takeaway": "对照成熟度模型评估企业AI治理现状，制定升级路径",
        "views": 360000,
        "engagement": 3100,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "AI原生应用架构：从RAG到Agent的范式转移",
        "url": "https://martinfowler.com/articles/ai-native-architecture-2026.html",
        "time_published": "2026-05-25T11:00:00+00:00",
        "source": "Martin Fowler",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI原生架构,RAG,Agent,范式转移 paradigm shift,系统设计",
        "summary": "AI原生应用架构从RAG到Agent范式转移，系统设计原则变革（AI-native architecture shifts from RAG to Agent paradigm）",
        "why_hot": "AI原生应用架构范式转移，系统设计原则变革",
        "takeaway": "重构应用架构以Agent为中心，而非简单嵌入AI功能",
        "views": 420000,
        "engagement": 3600,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "AI招聘伦理：算法偏见如何影响人才选拔公平性",
        "url": "https://www.shrm.org/topics-tools/news/hr-magazine/ai-recruiting-ethics-bias-2026",
        "time_published": "2026-05-18T09:00:00+00:00",
        "source": "SHRM",
        "category": "commentary",
        "tags": "AI;HR",
        "keywords": "AI招聘,算法偏见 algorithmic bias,人才选拔 fairness,伦理 ethics",
        "summary": "SHRM分析AI招聘算法偏见对人才选拔公平性的影响，提出审计框架（SHRM: how AI recruiting bias affects fairness, with audit framework）",
        "why_hot": "AI招聘算法偏见引发公平性担忧，审计需求上升",
        "takeaway": "建立AI招聘工具偏见审计机制，确保选拔公平性",
        "views": 440000,
        "engagement": 3800,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "AI编程生产力实证研究：真实ROI数据揭示",
        "url": "https://www.microsoft.com/en-us/research/publication/ai-coding-productivity-roi-2026/",
        "time_published": "2026-06-02T15:00:00+00:00",
        "source": "Microsoft Research",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI编程,生产力 productivity,ROI 实证研究,代码质量,开发者体验",
        "summary": "微软研究实证AI编程生产力提升26%-55%，但代码质量与可维护性需关注（Microsoft study: AI coding boosts productivity 26-55%, but quality concerns remain）",
        "why_hot": "AI编程生产力提升实证数据出炉，ROI可量化",
        "takeaway": "量化AI编程工具ROI，同时关注代码可维护性与技术债",
        "views": 510000,
        "engagement": 4400,
        "domain_weight": 1.5,
        "language": "zh",
    },
    {
        "title": "AI监管科技RegTech：合规自动化的新蓝海",
        "url": "https://www.financialtimes.com/content/regtech-ai-compliance-automation-2026",
        "time_published": "2026-06-13T08:00:00+00:00",
        "source": "Financial Times",
        "category": "commentary",
        "tags": "AI;HR服务",
        "keywords": "RegTech,合规自动化 compliance automation,监管科技,AI合规,蓝海市场",
        "summary": "AI驱动RegTech合规自动化成新蓝海，金融服务领先采用（AI-driven RegTech compliance automation becomes a blue ocean market）",
        "why_hot": "AI RegTech合规自动化成新蓝海市场",
        "takeaway": "评估AI合规自动化工具对HR与财务流程的降本价值",
        "views": 380000,
        "engagement": 3300,
        "domain_weight": 2.0,
        "language": "zh",
    },
    {
        "title": "AI数据中心能源危机：算力增长的电力瓶颈与绿色方案",
        "url": "https://www.iea.org/reports/ai-data-center-energy-crisis-2026",
        "time_published": "2026-06-09T10:00:00+00:00",
        "source": "IEA",
        "category": "commentary",
        "tags": "AI",
        "keywords": "AI数据中心,能源危机 energy crisis,电力瓶颈,绿色方案,可持续",
        "summary": "IEA报告AI数据中心电力消耗2026年翻倍，绿色能源方案成关键（IEA: AI data center power consumption doubles in 2026, green solutions critical）",
        "why_hot": "AI算力增长遭遇电力瓶颈，能源危机浮现",
        "takeaway": "评估AI部署的能源成本与可持续性，规划绿色算力",
        "views": 460000,
        "engagement": 3900,
        "domain_weight": 1.8,
        "language": "zh",
    },

    # ============ 社交 Social (25条) ============
    {
        "title": "Forbes宣布马斯克成为世界首位万亿富翁（Reddit热议）",
        "url": "https://www.reddit.com/r/singularity/comments/musk_trillionaire_2026/",
        "time_published": "2026-06-12T15:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "万亿富翁 trillionaire,马斯克 Musk,SpaceX,AI造富",
        "summary": "Forbes宣布马斯克成万亿富翁，Reddit r/singularity热议AI造富效应（Reddit r/singularity erupts as Forbes declares Musk first trillionaire）",
        "why_hot": "SpaceX估值推动马斯克成万亿富翁，AI造富效应震惊全球",
        "takeaway": "关注AI产业链估值泡沫与真实价值创造的区别",
        "views": 950000,
        "engagement": 8900,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "SpaceX 600亿美元洽购Cursor引发社区热议（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/spacex_cursor_anysphere_acquisition/",
        "time_published": "2026-06-17T16:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "SpaceX,Cursor,600亿美元,AI编程收购,航天-AI融合",
        "summary": "SpaceX洽购Cursor引发社区热议，1614评分450评论讨论航天AI融合（Reddit erupts: SpaceX in talks to buy Cursor for $60B, 1614 upvotes）",
        "why_hot": "航天巨头收购AI编程工具引发社区热议",
        "takeaway": "关注跨行业AI工具并购趋势对开发者生态的影响",
        "views": 780000,
        "engagement": 7200,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "GLM-5.2成首个TruthfulQA破80%开放权重模型（Reddit）",
        "url": "https://www.reddit.com/r/LocalLLaMA/comments/glm-5-2-truthfulqa-80-percent/",
        "time_published": "2026-06-17T14:00:00+00:00",
        "source": "Reddit r/LocalLLaMA",
        "category": "social",
        "tags": "AI",
        "keywords": "GLM-5.2,TruthfulQA 80%,开放权重 open-weight,MIT许可",
        "summary": "智谱GLM-5.2突破TruthfulQA 80%里程碑，开源模型性能首次追平闭源（Zhipu GLM-5.2 breaks 80% TruthfulQA, first open-weight to match closed-source）",
        "why_hot": "智谱GLM-5.2突破TruthfulQA 80%里程碑，开源首次追平闭源",
        "takeaway": "评估开源模型替代闭源方案的可行性，降低API依赖",
        "views": 690000,
        "engagement": 6100,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "美国政府指令暂停访问Fable 5和Mythos 5（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/us-government-fable-mythos-pause/",
        "time_published": "2026-06-12T20:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "Fable 5,Mythos 5,政府封禁,监管争议,国家安全",
        "summary": "美国政府封禁闭源模型引发监管与国家安全辩论，2378评分（Reddit: US government pause on Fable 5/Mythos 5 sparks regulation debate, 2378 upvotes）",
        "why_hot": "美国政府封禁闭源模型引发监管与国家安全辩论",
        "takeaway": "关注AI模型访问政策变化，建立多模型冗余策略",
        "views": 620000,
        "engagement": 5500,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Anthropic关闭生命科学研究路径API（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/anthropic-bio-research-api-closure/",
        "time_published": "2026-06-12T17:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "Anthropic,生命科学 API,封锁生物研究,安全限制",
        "summary": "Anthropic封锁生物研究API，独立研究者被迫转向本地模型（Reddit: Anthropic closes bio research API, independent researchers forced to local models）",
        "why_hot": "Anthropic封锁生物研究API，独立研究者被迫转向本地模型",
        "takeaway": "建立本地模型备用方案，避免单一API供应商断供风险",
        "views": 440000,
        "engagement": 3800,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Ladybird放弃公开PR模式：AI生成垃圾PR涌入开源项目（HN）",
        "url": "https://news.ycombinator.com/item?id=ladybird-public-pr-pause-2026",
        "time_published": "2026-06-06T13:30:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "AI生成PR,开源维护,Ladybird,垃圾贡献,质量危机",
        "summary": "AI降低伪造善意代码成本导致开源项目被垃圾PR淹没，797评分（HN: Ladybird pauses public PRs as AI spam overwhelms, 797 points）",
        "why_hot": "AI降低伪造善意代码成本导致开源项目被垃圾PR淹没",
        "takeaway": "建立代码贡献质量门槛机制，抵御AI生成垃圾提交",
        "views": 410000,
        "engagement": 3500,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Anthropic开源AI自主漏洞发现与修复参考框架（HN）",
        "url": "https://news.ycombinator.com/item?id=anthropic-recon-find-triage-patch",
        "time_published": "2026-06-06T16:30:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "漏洞发现 vulnerability,Claude Security,AI自主修复,gVisor沙箱",
        "summary": "Anthropic开源自主漏洞发现框架recon-find-triage-patch，517评分（HN: Anthropic open-sources autonomous vulnerability framework, 517 points）",
        "why_hot": "Anthropic开源自主漏洞发现框架，AI安全工具可复用",
        "takeaway": "评估AI安全扫描工具用于企业代码审计的可行性",
        "views": 360000,
        "engagement": 3100,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Meta智能眼镜内置面部识别管道引发隐私争议（HN）",
        "url": "https://news.ycombinator.com/item?id=meta-glasses-face-recognition-2026",
        "time_published": "2026-06-06T18:30:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "Meta眼镜,面部识别 face-recognition,隐私 privacy,SCRFD",
        "summary": "Meta眼镜内置完整人脸检测匹配管道但未开放用户界面，309评分（HN: Meta glasses contain hidden face recognition pipeline, 309 points）",
        "why_hot": "Meta眼镜内置面部识别管道未开放界面，隐私争议升级",
        "takeaway": "审查可穿戴设备AI功能的隐私合规与数据本地化方案",
        "views": 390000,
        "engagement": 3300,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "AI对软件工程职业冲击讨论（HN热门）",
        "url": "https://news.ycombinator.com/item?id=ai-software-engineering-career-impact",
        "time_published": "2026-06-08T10:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI;HR",
        "keywords": "AI冲击,软件工程 career,初级岗位减少,职业转型",
        "summary": "HN热议AI对软件工程职业的冲击，初级开发岗位减少近20%（HN: debate on AI's impact on software engineering careers, entry-level jobs down 20%）",
        "why_hot": "HN热议AI对软件工程职业的冲击，初级开发岗位减少近20%",
        "takeaway": "从基础编码转向系统设计与Agent安全运维，提升复合能力",
        "views": 480000,
        "engagement": 4100,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "特朗普政府认为强制开源AI模型是\"愚蠢的\"（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/white-house-open-weights-memo/",
        "time_published": "2026-06-17T20:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "开源强制,特朗普政府,安全审计,白宫备忘录",
        "summary": "白宫备忘录主张安全审计替代开放权重，引发开源vs闭源政策争议（Reddit: White House memo opposes mandatory open weights, favors security audits）",
        "why_hot": "白宫反对强制开源AI模型，开源vs闭源政策争议升级",
        "takeaway": "关注各国开源政策差异，提前布局跨境合规策略",
        "views": 370000,
        "engagement": 3200,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Figure AI机器人持续运行200小时里程碑（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/figure-ai-200-hour-milestone/",
        "time_published": "2026-06-08T13:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "Figure AI,机器人运行200小时,持续运行 endurance,里程碑",
        "summary": "Figure AI机器人突破200小时持续运行，Reddit月度评分4085（Reddit: Figure AI robot achieves 200-hour endurance, monthly score 4085）",
        "why_hot": "Figure AI机器人突破200小时持续运行，具身智能里程碑",
        "takeaway": "关注具身智能对HR服务行业中体力岗位的替代潜力",
        "views": 520000,
        "engagement": 4500,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "索尼AI Ace机器人击败职业选手Miyu（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/sony-ace-gran-turismo-miyu-victory/",
        "time_published": "2026-06-10T11:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "Sony AI,Ace机器人,职业选手 professional,竞技 defeat",
        "summary": "AI机器人首次在正式竞技比赛中击败人类职业选手，Reddit评分2938（Reddit: Sony AI Ace defeats pro racer Miyu, monthly score 2938）",
        "why_hot": "AI机器人首次在正式竞技比赛中击败人类职业选手",
        "takeaway": "关注AI竞技表现对人才评估标准与技能定义的潜在冲击",
        "views": 460000,
        "engagement": 3900,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Gemini Omni视频处理优势演示（Reddit）",
        "url": "https://www.reddit.com/r/singularity/comments/gemini-omni-video-demo/",
        "time_published": "2026-05-21T15:00:00+00:00",
        "source": "Reddit r/singularity",
        "category": "social",
        "tags": "AI",
        "keywords": "Gemini Omni,视频处理 video,视频操控,世界模型",
        "summary": "Gemini Omni视频操控能力成为新突破点，Reddit月度评分3650（Reddit: Gemini Omni video manipulation breakthrough, monthly score 3650）",
        "why_hot": "Gemini Omni视频操控能力成为新突破点",
        "takeaway": "评估视频AI对HR培训视频制作与远程面试的技术赋能",
        "views": 430000,
        "engagement": 3700,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Claude Opus 4.8编程能力实测：SWE-Pro 69.2%领先（HN）",
        "url": "https://news.ycombinator.com/item?id=claude-opus-4-8-swe-pro-benchmark",
        "time_published": "2026-05-28T17:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "Claude Opus 4.8,SWE-Pro 69.2%,编程能力 benchmark,实测",
        "summary": "Claude Opus 4.8 SWE-Pro 69.2%编程能力登顶，HN社区实测讨论（HN: Claude Opus 4.8 tops SWE-Pro at 69.2%, community benchmarks）",
        "why_hot": "Claude Opus 4.8编程能力登顶，企业开发场景首选",
        "takeaway": "评估Claude Opus 4.8在代码生成与软件工程任务的ROI",
        "views": 540000,
        "engagement": 4600,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "DeepSeek-V4-Pro开源推理模型登顶GPQA（HN）",
        "url": "https://news.ycombinator.com/item?id=deepseek-v4-pro-gpqa-top",
        "time_published": "2026-04-24T10:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "DeepSeek-V4-Pro,GPQA 90.1%,开源推理 open-source reasoning,MoE",
        "summary": "DeepSeek V4-Pro登顶开源推理GPQA 90.1%，HN社区热议成本优势（HN: DeepSeek V4-Pro tops open-source reasoning GPQA at 90.1%）",
        "why_hot": "国产开源模型推理能力首次全球登顶，成本优势显著",
        "takeaway": "评估DeepSeek开源模型在高推理任务的成本效益",
        "views": 490000,
        "engagement": 4200,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Anthropic呼吁放缓AI研发引发社区大讨论（HN）",
        "url": "https://news.ycombinator.com/item?id=anthropic-slow-down-ai-r-d-appeal",
        "time_published": "2026-05-28T16:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "AI自进化,递归自我改进 recursive self-improvement,安全风险,2028",
        "summary": "Anthropic呼吁放缓研发引发HN大讨论，预估2028年60%自进化概率（HN: Anthropic's slow-down appeal sparks debate, 60% self-improvement by 2028）",
        "why_hot": "Anthropic公开呼吁放缓研发，称AI进步过快递归风险上升",
        "takeaway": "建立AI部署伦理审查机制，关注递归自我改进风险信号",
        "views": 670000,
        "engagement": 5800,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "微软Build 2026 MAI模型自研脱离OpenAI（HN）",
        "url": "https://news.ycombinator.com/item?id=microsoft-build-2026-mai-models",
        "time_published": "2026-06-02T17:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "MAI模型,微软 Build,自研 in-house,稀疏MoE,10倍降本",
        "summary": "微软自研7款MAI模型标志从OpenAI依赖转向自主AI平台（HN: Microsoft's 7 in-house MAI models signal shift from OpenAI dependency）",
        "why_hot": "微软自研7款AI模型标志从OpenAI依赖转向自主AI平台",
        "takeaway": "评估多云多模型策略，避免单一供应商锁定",
        "views": 450000,
        "engagement": 3900,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Meta 148亿美元收购Scale AI引发讨论（HN）",
        "url": "https://news.ycombinator.com/item?id=meta-scale-ai-acquisition-2026",
        "time_published": "2026-06-09T12:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "Meta,Scale AI,超级智能 superintelligence,Alexandr Wang",
        "summary": "Meta拟148亿美元收购Scale AI 49%股份组建超级智能实验室（HN: Meta's $14.8B Scale AI deal sparks superintelligence lab discussion）",
        "why_hot": "Meta豪掷148亿美元收购数据标注龙头，战略转向超级智能",
        "takeaway": "关注数据标注供应链整合对AI训练数据质量的影响",
        "views": 510000,
        "engagement": 4400,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "AI招聘工具偏见引发LinkedIn HR从业者热议",
        "url": "https://www.linkedin.com/pulse/ai-recruiting-bias-hr-discussion-2026",
        "time_published": "2026-05-20T09:00:00+00:00",
        "source": "LinkedIn",
        "category": "social",
        "tags": "AI;HR",
        "keywords": "AI招聘,算法偏见 algorithmic bias,HR从业者,公平性 fairness",
        "summary": "AI招聘工具偏见引发LinkedIn HR从业者热议，审计需求上升（LinkedIn: HR professionals debate AI recruiting bias, audit demand rises）",
        "why_hot": "AI招聘算法偏见引发公平性担忧，HR从业者热议",
        "takeaway": "建立AI招聘工具偏见审计机制，确保选拔公平性",
        "views": 380000,
        "engagement": 3300,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Agent元年讨论：Databricks宣布Agent成为数据一等公民（HN）",
        "url": "https://news.ycombinator.com/item?id=databricks-agent-first-class-citizen",
        "time_published": "2026-06-15T17:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI;HR",
        "keywords": "Databricks DAIS,Agent一等公民,AI Gateway,Agent Bricks",
        "summary": "Databricks宣布Agent成为数据一等公民，HN讨论企业Agent平台影响（HN: Databricks declares agents first-class data citizens）",
        "why_hot": "Databricks宣布Agent成为数据一等公民，发布完整Agent平台",
        "takeaway": "评估Agent平台对HR数据分析与自动化决策的应用场景",
        "views": 420000,
        "engagement": 3600,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Apple WWDC Siri AI跨应用能力引发X平台热议",
        "url": "https://x.com/apple/siri-ai-wwdc-2026-discussion",
        "time_published": "2026-06-09T17:00:00+00:00",
        "source": "X (Twitter)",
        "category": "social",
        "tags": "AI",
        "keywords": "Siri AI,WWDC 2026,跨应用 cross-app,上下文理解,讨论",
        "summary": "苹果Siri AI跨应用执行任务能力引发X平台热议，设备端AI成焦点（X: Apple Siri AI cross-app capabilities spark device-side AI discussion）",
        "why_hot": "苹果正式进入AI优先时代，Siri深度整合大模型",
        "takeaway": "评估设备端AI部署对隐私合规的优势与局限",
        "views": 560000,
        "engagement": 4800,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "英伟达GTC Cosmos 3世界模型引发Reddit讨论",
        "url": "https://www.reddit.com/r/MachineLearning/comments/nvidia-cosmos-3-world-model/",
        "time_published": "2026-06-02T10:00:00+00:00",
        "source": "Reddit r/MachineLearning",
        "category": "social",
        "tags": "AI",
        "keywords": "NVIDIA GTC,Cosmos 3,Vera Rubin,RTX Spark,世界模型",
        "summary": "英伟达Cosmos 3世界模型引发r/MachineLearning讨论，物理AI前景分析（Reddit r/ML: NVIDIA Cosmos 3 world model sparks physical AI discussion）",
        "why_hot": "英伟达发布新一代世界模型与芯片架构推动物理AI",
        "takeaway": "关注世界模型对HR培训模拟与虚拟面试场景的应用前景",
        "views": 390000,
        "engagement": 3400,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "OpenAI重组安全团队人才流动引发HN讨论",
        "url": "https://news.ycombinator.com/item?id=openai-safety-team-anthropic-researcher",
        "time_published": "2026-06-07T16:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI",
        "keywords": "OpenAI,安全团队重组,Safety Team,Anthropic研究员,人才流动",
        "summary": "OpenAI重组安全团队引入前Anthropic研究员，HN讨论AI安全人才流动（HN: OpenAI safety team restructure with ex-Anthropic researcher）",
        "why_hot": "AI安全人才流动加剧，OpenAI强化对齐研究投入",
        "takeaway": "关注AI安全人才市场动态，评估企业安全团队建设",
        "views": 350000,
        "engagement": 3000,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "欧盟AI Act首批执法案例LinkedIn合规专家讨论",
        "url": "https://www.linkedin.com/pulse/eu-ai-act-first-enforcement-cases-compliance",
        "time_published": "2026-06-14T13:00:00+00:00",
        "source": "LinkedIn",
        "category": "social",
        "tags": "AI;HR",
        "keywords": "欧盟AI Act,高风险分类,执法案例 enforcement,合规,GDPR",
        "summary": "欧盟AI Act首批执法案例落地，LinkedIn合规专家讨论HR招聘系统影响（LinkedIn: EU AI Act first enforcement cases, HR systems impact）",
        "why_hot": "欧盟AI Act首批执法案例落地，HR招聘系统首当其冲",
        "takeaway": "审查HR AI工具合规性，确保符合EU AI Act高风险分类",
        "views": 410000,
        "engagement": 3500,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "斯坦福AI Index初级岗位减少20%引发HN职业讨论",
        "url": "https://news.ycombinator.com/item?id=stanford-ai-index-entry-level-jobs",
        "time_published": "2026-06-04T11:00:00+00:00",
        "source": "Hacker News",
        "category": "social",
        "tags": "AI;HR",
        "keywords": "AI Index,Stanford,初级岗位减少 20%,劳动力转型 workforce",
        "summary": "斯坦福AI Index揭示初级开发岗位减少近20%，HN热议职业转型方向（HN: Stanford AI Index entry-level jobs down 20%, career pivot debate）",
        "why_hot": "Stanford AI Index揭示初级开发岗位减少近20%，劳动力转型加速",
        "takeaway": "工程师需从基础编码转向高层系统设计与Agent运行时安全",
        "views": 470000,
        "engagement": 4000,
        "domain_weight": 1.0,
        "language": "zh",
    },

    # ============ 视频 Video (15条) ============
    {
        "title": "WWDC 2026 Siri AI深度演示：跨应用执行任务与上下文理解",
        "url": "https://www.youtube.com/watch?v=wwdc-2026-siri-ai-demo",
        "time_published": "2026-06-09T16:00:00+00:00",
        "source": "Apple/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Siri AI,WWDC 2026,跨应用 cross-app,上下文理解,演示",
        "summary": "苹果Siri AI首次完整演示跨应用任务执行与屏幕内容理解（Apple Siri AI demo: full cross-app task execution and screen content understanding）",
        "why_hot": "苹果Siri AI首次完整演示跨应用任务执行",
        "takeaway": "评估Siri AI对企业移动办公场景的自动化潜力",
        "views": 1200000,
        "engagement": 11000,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Anthropic Claude Fable 5发布视频：Mythos级模型能力展示",
        "url": "https://www.youtube.com/watch?v=anthropic-claude-fable-5-demo",
        "time_published": "2026-06-09T15:00:00+00:00",
        "source": "Anthropic/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Claude Fable 5,Mythos级,软件工程,视觉任务,安全护栏",
        "summary": "Anthropic首个公开Mythos级模型发布视频展示卓越编程与视觉能力（Anthropic: first public Mythos-tier model showcases coding and vision）",
        "why_hot": "Anthropic首个公开Mythos级模型发布视频展示能力",
        "takeaway": "关注Mythos级模型对企业开发流程的变革性影响",
        "views": 850000,
        "engagement": 7600,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Databricks Data+AI Summit 2026主题演讲：Agent成为数据一等公民",
        "url": "https://www.youtube.com/watch?v=databricks-dais-2026-keynote",
        "time_published": "2026-06-15T17:00:00+00:00",
        "source": "Databricks/YouTube",
        "category": "video",
        "tags": "AI;HR",
        "keywords": "Databricks DAIS,Agent一等公民,AI Gateway,Agent Bricks",
        "summary": "Databricks宣布Agent成为企业数据一等公民，发布完整Agent平台（Databricks DAIS 2026 keynote: agents as first-class data citizens）",
        "why_hot": "Databricks宣布Agent成为数据一等公民，发布完整Agent平台",
        "takeaway": "评估Agent平台对HR数据分析与自动化决策的应用场景",
        "views": 620000,
        "engagement": 5400,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "微软Build 2026主题演讲：7款MAI模型与Windows AI Agent平台",
        "url": "https://www.youtube.com/watch?v=microsoft-build-2026-keynote",
        "time_published": "2026-06-02T17:00:00+00:00",
        "source": "Microsoft/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "微软 Build 2026,MAI模型,Windows Agent平台,Copilot",
        "summary": "微软发布7款自研AI模型并将Windows定位为AI Agent平台（Microsoft Build 2026: 7 MAI models and Windows as AI Agent platform）",
        "why_hot": "微软发布7款自研AI模型并将Windows定位为Agent平台",
        "takeaway": "关注Windows Agent平台对企业办公自动化生态的重塑",
        "views": 720000,
        "engagement": 6300,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Google I/O 2026主题演讲：Gemini 3.5 Flash、Omni世界模型与Spark Agent",
        "url": "https://www.youtube.com/watch?v=google-io-2026-keynote",
        "time_published": "2026-05-20T18:00:00+00:00",
        "source": "Google/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Google I/O,Gemini 3.5,Omni世界模型,Spark Agent,1800亿投资",
        "summary": "Google三大Gemini新品齐发，1800亿美元布局AI基础设施（Google I/O 2026: Gemini 3.5, Omni world model, Spark Agent, $180B investment）",
        "why_hot": "Google三大Gemini新品齐发，1800亿美元布局AI基础设施",
        "takeaway": "评估Gemini Omni视频生成与Spark Agent对企业内容创作的价值",
        "views": 950000,
        "engagement": 8400,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "英伟达GTC Taipei 2026：Cosmos 3世界模型与RTX Spark芯片发布",
        "url": "https://www.youtube.com/watch?v=nvidia-gtc-taipei-2026-keynote",
        "time_published": "2026-06-02T10:00:00+00:00",
        "source": "NVIDIA/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "NVIDIA GTC,Cosmos 3,Vera Rubin,RTX Spark,世界模型",
        "summary": "英伟达发布Cosmos 3世界模型与新芯片架构推动物理AI（NVIDIA GTC Taipei: Cosmos 3 world model and Vera Rubin chips）",
        "why_hot": "英伟达发布新一代世界模型与芯片架构推动物理AI",
        "takeaway": "关注世界模型对HR培训模拟与虚拟面试场景的应用前景",
        "views": 680000,
        "engagement": 5900,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "ICRA 2026维也纳：华人学者斩获核心大奖，机器人界\"奥斯卡\"",
        "url": "https://www.youtube.com/watch?v=icra-2026-vienna-awards",
        "time_published": "2026-06-05T14:00:00+00:00",
        "source": "IEEE ICRA/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "ICRA 2026,华人学者,机器人大奖,维也纳 Vienna",
        "summary": "全球机器人顶级会议华人学者斩获多项大奖，标志研究实力崛起（ICRA 2026 Vienna: Chinese researchers win multiple robotics awards）",
        "why_hot": "全球机器人顶级会议华人学者斩获多项大奖",
        "takeaway": "关注机器人技术对HR服务自动化与现场招聘的潜在应用",
        "views": 420000,
        "engagement": 3600,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Figure AI机器人持续运行200小时里程碑视频",
        "url": "https://www.youtube.com/watch?v=figure-ai-200-hour-endurance",
        "time_published": "2026-06-08T13:00:00+00:00",
        "source": "Figure AI/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Figure AI,机器人运行200小时,持续运行 endurance,里程碑",
        "summary": "Figure AI机器人突破200小时持续运行，具身智能进入实用阶段（Figure AI robot achieves 200-hour continuous operation milestone）",
        "why_hot": "Figure AI机器人突破200小时持续运行，具身智能里程碑",
        "takeaway": "关注具身智能对HR服务行业中体力岗位的替代潜力",
        "views": 580000,
        "engagement": 5000,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "索尼AI Ace机器人击败职业选手Miyu比赛完整视频",
        "url": "https://www.youtube.com/watch?v=sony-ace-gran-turismo-miyu-race",
        "time_published": "2026-06-10T11:00:00+00:00",
        "source": "Sony AI/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Sony AI,Ace机器人,职业选手 professional,竞技 defeat",
        "summary": "索尼AI Ace机器人在Gran Turismo正式比赛击败职业选手Miyu（Sony AI Ace defeats professional racer Miyu in official Gran Turismo match）",
        "why_hot": "AI机器人首次在正式竞技比赛中击败人类职业选手",
        "takeaway": "关注AI竞技表现对人才评估标准与技能定义的潜在冲击",
        "views": 920000,
        "engagement": 8100,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Gemini Omni视频处理优势官方演示",
        "url": "https://www.youtube.com/watch?v=google-gemini-omni-video-demo",
        "time_published": "2026-05-21T16:00:00+00:00",
        "source": "Google/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Gemini Omni,视频处理 video,视频操控,世界模型",
        "summary": "Gemini Omni视频操控能力成为新突破点，Google官方演示（Google official demo: Gemini Omni video manipulation breakthrough）",
        "why_hot": "Gemini Omni视频操控能力成为新突破点",
        "takeaway": "评估视频AI对HR培训视频制作与远程面试的技术赋能",
        "views": 710000,
        "engagement": 6200,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "Claude Opus 4.8编程能力实测对比视频",
        "url": "https://www.youtube.com/watch?v=claude-opus-4-8-coding-comparison",
        "time_published": "2026-05-28T18:00:00+00:00",
        "source": "技术测评/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "Claude Opus 4.8,SWE-Pro 69.2%,编程能力 benchmark,实测对比",
        "summary": "Claude Opus 4.8 SWE-Pro 69.2%编程能力实测对比，企业开发首选（Claude Opus 4.8 coding comparison: SWE-Pro 69.2% leads enterprise）",
        "why_hot": "Claude Opus 4.8编程能力登顶，企业开发场景首选",
        "takeaway": "评估Claude Opus 4.8在代码生成与软件工程任务的ROI",
        "views": 540000,
        "engagement": 4700,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "DeepSeek-V4-Pro开源推理模型能力解析视频",
        "url": "https://www.youtube.com/watch?v=deepseek-v4-pro-analysis",
        "time_published": "2026-04-24T11:00:00+00:00",
        "source": "技术解析/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "DeepSeek-V4-Pro,GPQA 90.1%,开源推理 open-source reasoning,MoE",
        "summary": "DeepSeek V4-Pro登顶开源推理GPQA 90.1%，成本优势解析（DeepSeek V4-Pro: tops open-source reasoning GPQA 90.1%, cost advantage analysis）",
        "why_hot": "国产开源模型推理能力首次全球登顶，成本优势显著",
        "takeaway": "评估DeepSeek开源模型在高推理任务的成本效益",
        "views": 480000,
        "engagement": 4100,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "AI Agent企业落地实战教程：从Demo到生产",
        "url": "https://www.youtube.com/watch?v=ai-agent-production-deployment-tutorial",
        "time_published": "2026-06-09T10:00:00+00:00",
        "source": "技术教程/YouTube",
        "category": "video",
        "tags": "AI;HR",
        "keywords": "AI Agent,企业落地 production,Demo到生产,最佳实践,教程",
        "summary": "AI Agent企业落地实战教程，从Demo到生产的工程化最佳实践（AI Agent production deployment tutorial: from demo to production best practices）",
        "why_hot": "AI Agent企业落地实战教程填补工程化空白",
        "takeaway": "建立Agent生产化检查清单，避免Demo到生产陷阱",
        "views": 390000,
        "engagement": 3400,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "AI招聘工具实操演示：如何避免算法偏见",
        "url": "https://www.youtube.com/watch?v=ai-recruiting-bias-avoidance-tutorial",
        "time_published": "2026-05-20T11:00:00+00:00",
        "source": "HR Tech/YouTube",
        "category": "video",
        "tags": "AI;HR",
        "keywords": "AI招聘,算法偏见 algorithmic bias,公平性 fairness,审计 audit,实操",
        "summary": "AI招聘工具实操演示，如何避免算法偏见确保选拔公平性（AI recruiting tool demo: how to avoid algorithmic bias for fairness）",
        "why_hot": "AI招聘工具偏见审计实操演示，HR从业者关注",
        "takeaway": "建立AI招聘工具偏见审计机制，确保选拔公平性",
        "views": 320000,
        "engagement": 2800,
        "domain_weight": 1.0,
        "language": "zh",
    },
    {
        "title": "AI算力投资指南：万卡集群采购与运营全解析",
        "url": "https://www.youtube.com/watch?v=ai-compute-investment-10k-gpu-guide",
        "time_published": "2026-05-15T12:00:00+00:00",
        "source": "技术财经/YouTube",
        "category": "video",
        "tags": "AI",
        "keywords": "AI算力,万卡集群,TCO 总拥有成本,投资回报 ROI,资本支出",
        "summary": "AI算力投资指南，万卡集群采购与运营TCO全解析（AI compute investment guide: 10K-GPU cluster procurement and TCO analysis）",
        "why_hot": "AI算力投资指南填补万卡集群TCO分析空白",
        "takeaway": "评估AI算力投资的TCO而非仅看采购成本",
        "views": 280000,
        "engagement": 2400,
        "domain_weight": 1.0,
        "language": "zh",
    },
]

print(f"种子数据加载完成: {len(SEED_ARTICLES)} 条")
